#1370 Support practional part of the day offset
dtcenter/MET pull request #1376
Opened 2020-06-12 21:09 UTC by hsoh-u

The test file at dakota: /d3/personal/hsoh/data/git_1370_fraction_of_day/MetPlus.globe.2014-08-01-00000.cam.h0.2014-08-01-10800.nc

- successful time selection (20140801_060000 by 92.125):
./plot_data_plane MetPlus.globe.2014-08-01-00000.cam.h0.2014-08-01-10800.nc tmp_test.ps 'name="T"; level="(20140801_060000,0,*,*)";' -v 4

- failed time selection because wrong time (20140801_000000):
./plot_data_plane MetPlus.globe.2014-08-01-00000.cam.h0.2014-08-01-10800.nc tmp_test.ps 'name="T"; level="(20140801_000000,0,*,*)";' -v 4

2020-06-12 21:16 UTC, hsoh-u commented
The two lines to avoid dead code:

  const char *ptr = getenv("MET_DEBUG");
  bool debug = (NULL != ptr && 0 < strlen(ptr));

bool debug =false;
...
if (debug) {   <=== dead code block
   ...
}

2020-06-12 22:55 UTC, JohnHalleyGotway commented on met/src/basic/vx_cal/is_leap_year.cc
> +  bool debug = (NULL != ptr && 0 < strlen(ptr));
```suggestion
  const char *ptr = getenv("MET_DEBUG");
  bool debug = (NULL != ptr && 0 < strlen(ptr));
```

Replace that with this
```
bool debug = mlog.verbosity_level() >= 5;
```
Or substitute in whatever level value you'd like.
I think that's preferable to introducing a new MET_DEBUG environment variable.

2020-06-12 22:56 UTC, JohnHalleyGotway requested changes
Recommend replacing MET_DEBUG environment variable with a check of the mlog.verbosity_level().

2020-06-12 23:54 UTC, JohnHalleyGotway commented on met/src/basic/vx_cal/is_leap_year.cc
> +  const char *ptr = getenv("MET_DEBUG");
```suggestion
  
```
If using mlog, then this "const char *ptr = getenv("MET_DEBUG") " is no longer needed and can be removed.

2020-06-12 23:55 UTC, JohnHalleyGotway requested changes
Just a one-line change.

2020-06-13 00:12 UTC, JohnHalleyGotway approved these changes

2020-06-13 00:12 UTC, merged