Feature 1764 point stat
dtcenter/MET pull request #1885
Opened 2021-08-20 17:58 UTC by sethlinden

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>

Initial testing was done by running a point_stat command line by hand from kiowa:

./point_stat /d1/personal/linden/git/feature_1764_point_stat/MET/MET_test_data/unit_test/model_data/met_nc/nam/nam_2012040900_F036_APCP24.nc /d1/personal/linden/git/feature_1764_point_stat/MET/test_output/ascii2nc/gauge_2012041012_24hr.nc /d1/personal/linden/git/feature_1764_point_stat/MET/test/config/PointStatConfig_APCP_HIRA -outdir /d1/personal/linden/git/feature_1764_point_stat/MET/test_output/hira -v 3

After adding ORANK to all of the point_stat config files, I ran "make test" to test all calls to point_stat. It was successful. Note, the generation of the ORANK output lines was only turned "on" for PointStatConfig_APCP_HIRA

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Run unit tests for MET (run "make test")

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes or No]**

Yes. I updated all relevant documentation in: docs/Users_Guide/point-stat.rst

- [x] Do these changes include sufficient testing updates? **[Yes or No]**

Yes, I updated all point_stat config files to list ORANK. Tested by running "make test".

- [x] Will this PR result in changes to the test suite? **[Yes or No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

Yes, this changes adds ORANK output lines to the output for: PointStatConfig_APCP_HIRA

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [ ] After submitting the PR, select **Linked issues** with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

2021-08-20 18:38 UTC, georgemccabe commented on met/src/tools/core/point_stat/point_stat_conf_info.cc
> +
```suggestion

```
Remove extra whitespace in blank line

2021-08-20 18:40 UTC, georgemccabe commented on met/src/tools/core/point_stat/point_stat.cc
> +	 //Compute ensemble statistics
```suggestion
         //Compute ensemble statistics
```
It looks like a mix of tabs and spaces here

2021-08-20 18:47 UTC, georgemccabe approved these changes
The code changes look good to me.

I did notice that there are some blank lines that now have some space characters and some lines that have a mix of tabs and spaces. It would be nice to clean that up, but it won't negatively impact the actual code so it is not imperative. I marked the 2 files with suggested changes to fix these, but I did not mark all of the instances of these cases in those files.

I didn't run the make tests but if you ran them successfully and @JohnHalleyGotway does as well, then I trust that they are correct.

I approve of these changes.

2021-08-20 18:50 UTC, JohnHalleyGotway reviewed
I'm going to run a full regression test for this PR. Please don't merge these changes until I get back to you with the results.

2021-08-20 18:56 UTC, sethlinden commented
Thanks George for giving this a review. Sorry about the mixture of tabs and spaces, I thought I had my emacs configured properly. I did have to manipulate some of the comments because they would not "tab over" with the backslashes (//). Do you by chance use emacs? Do you have an example .emacs file I can looks at.

2021-08-20 19:42 UTC, JohnHalleyGotway requested changes
@sethlinden at least one of the unit tests fails. Looks like you missed adding ORANK to at least one of the Point-Stat config files:
```
CALLING: /d1/projects/MET/MET_pull_requests/met-10.1.0/met-10.1.0_beta2/feature_1764/MET-feature_1764_point_stat/test/perl/unit.pl  /d1/projects/MET/MET_pull_requests/met-10.1.0/met-10.1.0_beta2/feature_1764/MET-feature_1764_point_stat/test/xml/unit_met_test_scripts.xml

TEST: test_all_gen_vx_mask_1     - pass -   0.546 sec
TEST: test_all_gen_vx_mask_2     - pass -   0.325 sec
TEST: test_all_pcp_combine_1     - pass -   3.157 sec
TEST: test_all_pcp_combine_2     - pass -   2.855 sec
TEST: test_all_pcp_combine_3     - pass -   5.353 sec
TEST: test_all_pcp_combine_4     - pass -   0.782 sec
TEST: test_all_pcp_combine_5     - pass -   0.717 sec
TEST: test_all_pcp_combine_6     - pass -   1.175 sec
TEST: test_all_mode_1            - pass -   4.054 sec
TEST: test_all_mode_2            - pass -   3.478 sec
TEST: test_all_mode_3            - pass -   4.482 sec
TEST: test_all_grid_stat_1       - pass -   0.627 sec
TEST: test_all_grid_stat_2       - pass -   0.327 sec
TEST: test_all_grid_stat_3       - pass -   0.919 sec
TEST: test_all_grid_stat_4       - pass -   5.618 sec
TEST: test_all_pb2nc             - pass -   9.015 sec
TEST: test_all_plot_point_obs    - pass -   5.280 sec
TEST: test_all_ascii2nc_1        - pass -   0.260 sec
TEST: test_all_ascii2nc_2        - pass -   0.359 sec
TEST: test_all_madis2nc          - pass -   1.077 sec
TEST: test_all_point_stat        - FAIL -   0.288 sec
/d1/projects/MET/MET_pull_requests/met-10.1.0/met-10.1.0_beta2/feature_1764/MET-feature_1764_point_stat/met/share/met/../../bin/point_stat \
      /d1/projects/MET/MET_pull_requests/met-10.1.0/met-10.1.0_beta2/feature_1764/MET-feature_1764_point_stat/met/data/sample_fcst/2007033000/nam.t00z.awip1236.tm00.20070330.grb \
      /d1/projects/MET/MET_pull_requests/met-10.1.0/met-10.1.0_beta2/feature_1764/MET-feature_1764_point_stat/test_output/met_test_scripts/pb2nc/sample_pb.nc \
      /d1/projects/MET/MET_pull_requests/met-10.1.0/met-10.1.0_beta2/feature_1764/MET-feature_1764_point_stat/met/scripts/config/PointStatConfig \
      -outdir /d1/projects/MET/MET_pull_requests/met-10.1.0/met-10.1.0_beta2/feature_1764/MET-feature_1764_point_stat/test_output/met_test_scripts/point_stat \
      -v 2
DEBUG 1: Default Config File: /d1/projects/MET/MET_pull_requests/met-10.1.0/met-10.1.0_beta2/feature_1764/MET-feature_1764_point_stat/met/share/met/config/PointStatConfig_default
DEBUG 1: User Config File: /d1/projects/MET/MET_pull_requests/met-10.1.0/met-10.1.0_beta2/feature_1764/MET-feature_1764_point_stat/met/scripts/config/PointStatConfig
ERROR  : 
ERROR  : Dictionary::lookup_int() -> lookup failed for name "output_flag.orank"
ERROR  : 

ERROR: /d1/projects/MET/MET_pull_requests/met-10.1.0/met-10.1.0_beta2/feature_1764/MET-feature_1764_point_stat/test/perl/unit.pl unit_met_test_scripts.xml failed.

*** UNIT TESTS FAILED ***
```

2021-08-20 22:48 UTC, JohnHalleyGotway commented
Finished reviewing the code changes and after a few commits, the code is all aligned and the point-stat/grid-stat docs are all consistent. Just waiting for the regression test to finish up...

2021-08-23 15:43 UTC, JohnHalleyGotway requested changes
The regression test reveals that output has changed in only 2 files:
```
cd /d1/projects/MET/MET_pull_requests/met-10.1.0/met-10.1.0_beta2/feature_1764
egrep -i "file1|error:" test_regression.log | egrep -B 1 ERROR: | grep file1
file1: MET-feature_1764_point_stat/test_output/hira/point_stat_HIRA_EMPTY_PROB_CAT_THRESH_360000L_20120410_120000V.stat
file1: MET-feature_1764_point_stat/test_output/hira/point_stat_NCMET_NAM_HMTGAGE_HIRA_360000L_20120410_120000V.stat
```
I found an issue in the setting of the OBS_VALID_BEG and OBS_VALID_END columns.
In point_stat_HIRA_EMPTY_PROB_CAT_THRESH_360000L_20120410_120000V.stat, for the RPS and ECNT line types, the values change.
FROM: 20120410_113000 20120410_123000
TO: 20120410_120000 20120410_120000

After writing the HiRA ORANK lines, reset the OBS_VALID_BEG and OBS_VALID_END columns back to what they had been. Please see this [line](https://github.com/dtcenter/MET/blob/6d7b55c25c022f80d847dde0ef661fec22a97cb1/met/src/tools/core/ensemble_stat/ensemble_stat.cc#L1418) from Ensemble-Stat and this [line](https://github.com/dtcenter/MET/blob/6d7b55c25c022f80d847dde0ef661fec22a97cb1/met/src/tools/core/point_stat/point_stat.cc#L1044) from Point-Stat, and do the same thing after calling write_orank_row(...).

2021-08-23 15:50 UTC, sethlinden commented
Hi John, thanks for letting me know about having to to reset OBS_VALID_BEG and OBS_VALID_END after calling write_orank_row. I'll make those changes now.

2021-08-23 17:26 UTC, JohnHalleyGotway approved these changes
I approve of these changes.

I re-ran unit_hira.xml with the latest changes from @sethlinden and confirmed that the only differences between the two Point-Stat output files are the addition of the new ORANK lines.

Note that this PR changes the output of the unit tests, so the regression test will fail. @JohnHalleyGotway will merge in these changes and then restart last night's nightly build.

2021-08-23 17:26 UTC, merged