Feature 1949 cf netcdf documentaton
dtcenter/MET pull request #1951
Opened 2021-10-26 15:18 UTC by hsoh-u

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>

No code changes. Added CF compliant NetCDF into Data IO.

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Review documentation: https://met.readthedocs.io/en/feature_1949_cf_netcdf/Users_Guide/data_io.html

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**

- [x] Do these changes include sufficient testing updates? **[No]**

- [x] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [ ] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [ ] After submitting the PR, select **Linked issues** with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

2021-10-26 22:05 UTC, jprestop commented on met/docs/Users_Guide/data_io.rst
> +MET tools uses following attributes and variables for the CF Compliant NetCDF.
```suggestion
The MET tools use the following attributes and variables for input CF-Compliant NetCDF data.
```

2021-10-26 22:06 UTC, jprestop commented on met/docs/Users_Guide/data_io.rst
> +MET processes the CF-Compliant gridded NetCDF files with the projection information. The CF-Compliant NetCDF is defined by the global attribute "Conventions" whose value begins with "CF-" ("CF-<Versi
```suggestion
MET processes the CF-Compliant gridded NetCDF files with the projection information. The CF-Compliant NetCDF is defined by the global attribute "Conventions" whose value begins with "CF-" ("CF-<Version_number>"). The global attribute "Conventions" is mandatory. MET accepts the variation of this attribute ("conventions" and "CONVENTIONS"). The value should be started with "CF-" and followed by the version number. MET accepts the attribute value that begins with "CF " ("CF" and a space instead of a hyphen) or "COARDS".
```

2021-10-26 22:08 UTC, jprestop commented on met/docs/Users_Guide/data_io.rst
> +2. The "standard_name" and "units" attributes for coordinate variables. The "axis" attribute ("T" or "time") must exist at the time variable if the "standard_name" attribute does not exist.
```suggestion
2. The "`standard_name <https://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#standard-name>`_" and "`units <https://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#units>`_" attributes for coordinate variables. The "`axis <https://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#time-axis-ex>`_" attribute ("T" or "time") must exist as the time variable if the "standard_name" attribute does not exist.
```

2021-10-26 22:09 UTC, jprestop commented on met/docs/Users_Guide/data_io.rst
> +3. The "coordinates" attribute at the data variables. It contains the coordinate variable names.
```suggestion
3. The "`coordinates <https://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#coordinate-types>`_" attribute for the data variables. It contains the coordinate variable names.
```

2021-10-26 22:10 UTC, jprestop commented on met/docs/Users_Guide/data_io.rst
> +4. The "grid_mapping" attribute at the data variables for projections and the matching grid mapping variable (optional for the latitude_longitude projection).
```suggestion
4. The "`grid_mapping <https://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#appendix-grid-mappings>`_" attribute for the data variables for projections and the matching grid mapping variable (optional for the latitude_longitude projection).
```

2021-10-26 22:10 UTC, jprestop commented on met/docs/Users_Guide/data_io.rst
> +6. (Optional) the "forecast_reference_time" variable for init_time.
```suggestion
6. (Optional) the "`forecast_reference_time <https://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#scalar-coordinate-variables>`_" variable for init_time.
```

2021-10-26 22:11 UTC, jprestop commented on met/docs/Users_Guide/data_io.rst
> +3. the lat/lon projection from the latitude and longitude variables by tte "standard_name" attribute
```suggestion
3. the lat/lon projection from the latitude and longitude variables by the "standard_name" attribute
```

2021-10-26 22:11 UTC, jprestop commented on met/docs/Users_Guide/data_io.rst
> +MET is looking for variables with the same name as the dimension and checking the "units" attribute to find the latitude and longitude variables. The valid "units" strings are listed at the table bel
```suggestion
MET is looking for variables with the same name as the dimension and checking the "units" attribute to find the latitude and longitude variables. The valid "units" strings are listed in the table below. MET accepts the variable "tlat" and "tlon" if the dimension names are "nlat" and "nlon”.
```

2021-10-26 22:12 UTC, jprestop commented on met/docs/Users_Guide/data_io.rst
> +MET gets the time, latitude, and the longitude variables by looking at the standard name: "time", "latitude", and "longitude" as the last option.
```suggestion
MET gets the time, latitude, and longitude variables by looking at the standard name: "time", "latitude", and "longitude" as the last option.
```

2021-10-26 22:16 UTC, jprestop requested changes
Thank you for writing all of this helpful documentation!  I particularly like the examples that you gave for both “Conventions” and “grid_mapping”. I reviewed the documentation and added a few suggestions for modifications, including adding links to the CF conventions documentation for the attributes and variables you mention in the documentation to make it easier for the users to find that information.  

With regard to what Marion was looking for (https://github.com/dtcenter/MET/issues/1949#issuecomment-948917941): 

> a) Size of input files (limits, implications etc); 

Are there any limitations with regard to size or anything else noteworthy with regard to size that we should include in the documentation?

> b) splitting files (e.g. keeping forecast ranges separate, can different variables be in the same file, is it ok to have multi-level data in one file, and implications for how to access this via the format string, do ensemble members need to be in separate files, "detecting"/specifying control members), 

Would you be able to address these questions more specifically in the documentation?  I did not see these questions addressed, but perhaps they were, because I don’t fully understand all of these questions?

> c) filenaming conventions and how MET diagnoses the time/date info and uses it for output file naming.

It looks like how MET diagnoses the time/date info was addressed, however, I did not see information about how MET “uses it for output file naming”. Perhaps that is based on the individual tool being used though?

@JohnHalleyGotway, would you be able to look this over as well, since you are more familiar with the technical details of MET?

2021-10-27 03:27 UTC, hsoh-u commented
- Made updates for the requested changes
- Added "Performance with NetCDF input data" section which covers issue 1 (file size) and the part of issue 2,

2021-10-27 19:32 UTC, jprestop commented on met/docs/Users_Guide/data_io.rst
> +2. The ""`standard_name <https://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#standard-name>`_" and "`units <https://cfconventions.org/Data/cf-conventions/cf-conventio
```suggestion
2. The "`standard_name <https://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#standard-name>`_" and "`units <https://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#units>`_" attributes for coordinate variables. The "`axis <https://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#time-axis-ex>`_" attribute ("T" or "time") must exist as the time variable if the "standard_name" attribute does not exist.
```

2021-10-27 19:34 UTC, jprestop commented on met/docs/Users_Guide/data_io.rst
> +There is no limitation on the NetCDF file size. The size of the data variables matters than the file size. NetCDF API loads the meta data first on opening the NetCDF. It's the similar on accesing dat
```suggestion
There is no limitation on the NetCDF file size. The size of the data variables matters more than the file size. The NetCDF API loads the metadata first upon opening the NetCDF file. It's similar for accessing data variables. There are two API calls: getting the metadata and getting the actual data. The memory is allocated and consumed at the second API call (getting the actual data).
```

2021-10-27 19:43 UTC, jprestop commented on met/docs/Users_Guide/data_io.rst
> +The dimensions of the data variables matter. MET requests the NetCDF data need based: 1) 1oading and processing a data plane, and 2) loading and processing the next data plane. This means an extra st
```suggestion
The dimensions of the data variables matter. MET requests the NetCDF data needs based on: 1) loading and processing a data plane, and 2) loading and processing the next data plane. This means an extra step for slicing with one more dimension in the NetCDF input data. The performance is quite different if the compression is enabled with high resolution data. NetCDF does compression per variable. The variables can have different compression levels (0 to 9).  A value of 0 means no compression, and 9 is the highest level of compression possible. The number for decompression is the same between one more and one less dimension NetCDF input files (combined VS separated). The difference is the amount of data to be decompressed which requires more memory. For example, let's assume the time dimension is 30. NetCDF data with one less dimension (no time dimension) does decompression 30 times for nx by ny dataset. NetCDF with one more dimension does compression 30 times for 30 by nx by ny dataset and slicing for target time offset. So it's better to have multiple NetCDF files with one less dimension than a big file with bigger variable data if compressed. If the compression is not enabled, the file size will be much bigger requiring more disk space.
```

2021-10-27 19:46 UTC, jprestop commented
@hsoh-u Thank you for adding the "Performance with NetCDF input data" section to help address Marion's questions.  I made a few other minor suggestions for changes.

2021-11-01 17:53 UTC, jprestop commented
Hi @hsoh-u. I see that you re-requested my review on this issue.  Please take a look at the additional suggested changes starting [here](https://github.com/dtcenter/MET/pull/1951#discussion_r737783549) in the PR and let me know if you have any questions.

2021-11-12 21:46 UTC, jprestop commented
@mpm-meto, in an email earlier I said "Marion, I'll wait for feedback from you by Monday early afternoon (Mountain time) before approving the pull request."  When I said this, I thought the our beta4 release was scheduled for Tuesday, but it is actually scheduled for Monday.  My apologies.  If you have time on Monday morning, could you please look this over?  I'll plan to go ahead and merge this in to develop on Monday morning (Mountain time) so it can make it into the release.  However, please don't hesitate to submit any feedback, even if it's been merged in before you have time to review it and we'll be sure to get that feedback into beta5 if we don't make it into beta4.

2021-11-15 16:01 UTC, jprestop approved these changes
The changes look good.  @TaraJensen has had an opportunity to review this as well and agrees.  I approve this PR.

2021-11-15 16:01 UTC, merged