Feature 2072 tc rmw winds
dtcenter/MET pull request #2165
Opened 2022-05-17 19:40 UTC by davidalbo

## Expected Differences ##

- [ ] Do these changes introduce new tools, command line arguments, or configuration file options? **[Yes]**</br>
If **yes**, please describe:</br>
New configuration file options were added to control conversion of winds:
```
//
// Optionally convert u/v winds to tangential/radial winds
//
compute_tangential_and_radial_winds = TRUE;
u_wind_field_name = "UGRD";
v_wind_field_name = "VGRD";
tangential_velocity_field_name = "VT";
tangential_velocity_long_field_name = "Tangential Velocity";
radial_velocity_field_name = "VR";
radial_velocity_long_field_name = "Radial Velocity";
```
- [ ] Do these changes modify the structure of existing or add new output data types (e.g. statistic line types or NetCDF variables)? **[Yes]**</br>
If **yes**, please describe:</br>
The tangential and radial velocity are new netCDF output variables.

## Pull Request Testing ##

- [ ] Describe testing already performed for these changes:</br>    The unit tests (2 of them) for this app were modified to include the new configuration parameters.  The tests ran successfully.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>   Possibly run the unit tests and then look at the output netCDF files where the new output fields can be seen.

- [ ] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes or No]**   Not sure.  Is there other documentation besides the user guide?

- [ ] Do these changes include sufficient testing updates? **[Yes or No]**  Not sure.  Are there other tests besides the unit tests?

- [ ] Will this PR result in changes to the test suite? **[Yes]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>  The output of the unit tests has new netCDF variables for radial and tangential winds.

- [ ] Please complete this pull request review by **[May 23, 2022]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [ ] After submitting the PR, select **Linked issues** with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

2022-05-19 16:13 UTC, JohnHalleyGotway commented
@davidalbo, I took a look at this PR and realize that the checks didn't look right because you branched from develop a long time ago. I'm going to do the following to try to get the checks to run:
```
git checkout develop; git pull # To get the latest version of develop
git checkout feature_2072_tc_rmw_winds; git pull # To get the latest from your feature branch
git merge develop # To merge develop into your feature branch
git push # To push the result back up to GitHub
```
I think that'll trigger the full set of tests to run... but will let you know.

2022-05-19 19:09 UTC, JohnHalleyGotway commented on src/tools/tc_utils/tc_rmw/tc_rmw_wind_converter.cc
> +    _computeWinds = false;
Everywhere else in MET, all ERROR messages are followed by a call to exit(1) to return bad status.
Recommend either exiting here, or change the "Error" messages to "Warning" instead.

2022-05-19 19:09 UTC, JohnHalleyGotway commented on src/tools/tc_utils/tc_rmw/tc_rmw_wind_converter.cc
> +      _computeWinds = false;
Everywhere else in MET, all ERROR messages are followed by a call to exit(1) to return bad status.
Recommend either exiting here, or change the "Error" messages to "Warning" instead.

2022-05-19 19:10 UTC, JohnHalleyGotway commented on src/tools/tc_utils/tc_rmw/tc_rmw_wind_converter.cc
> +	   << "field not found in input" << _conf->u_wind_field_name << "\n";
Everywhere else in MET, all ERROR messages are followed by a call to exit(1) to return bad status.
Recommend either exiting here, or change the "Error" messages to "Warning" instead.

```suggestion
	   << "field not found in input \"" << _conf->u_wind_field_name << "\"\n";
```

2022-05-19 19:10 UTC, JohnHalleyGotway commented on src/tools/tc_utils/tc_rmw/tc_rmw_wind_converter.cc
> +	   << "field not found in input" << _conf->v_wind_field_name << "\n";
Everywhere else in MET, all ERROR messages are followed by a call to exit(1) to return bad status.
Recommend either exiting here, or change the "Error" messages to "Warning" instead.

```suggestion
	   << "field not found in input \"" << _conf->v_wind_field_name << "\"\n";
```

2022-05-19 19:17 UTC, JohnHalleyGotway requested changes
- Please see individual comments about Error vs Warning messages. Either changes the errors to warnings or keep them as error and exit after printing the error message.
- Throughout MET we're using spaces rather than tabs for indents but keeping that consistent seems like a uphill battle/lost cause. Just wanted to mention it.

- After merging the latest from the develop branch into this feature branch... and rerunning bootstrap on seneca to regenerate the Makefile.in files... the GHA testing workflow ran. As expected, it flagged differences in 2 TCRMW output files, and none else:

tc_rmw_hwrf_gonzalo.nc and tc_rmw_pressure_lev_out.nc now contain 2 new output variables:
```
> 	double VR(range, azimuth, pressure, track_point) ;
> 		VR:long_name = "Radial Velocity" ;
> 		VR:units = "m/s" ;
> 		VR:_FillValue = -9999. ;
> 	double VT(range, azimuth, pressure, track_point) ;
> 		VT:long_name = "Tangential Velocity" ;
> 		VT:units = "m/s" ;
> 		VT:_FillValue = -9999. ;
```

To test further, I compiled this feature branch locally on seneca. I reconfigured/reran to confirm that...
- setting ```compute_tangential_and_radial_winds = FALSE;``` disables them.
- setting ```u_wind_field_name``` to a bad string triggers an error.
- changing the string names has the desired effect in the output.
- if UGRD and VGRD are NOT requested in the input, then the wind derivation errors out, as it should.

2022-05-20 13:13 UTC, davidalbo commented
Thanks for the thorough feedback @JohnHalleyGotway .  The spaces versus tabs thing...I understand the rationale, but.. I'm editing with emacs which puts in the tabs, making it very hard to comply.  Maybe there is a way to turn that off, not sure.

2022-05-20 20:51 UTC, JohnHalleyGotway approved these changes
I approve of these changes.

Thanks for switching those errors to warnings. As we discussed via email, I tweaked the wording to reference u/v winds. And I consolidated multiple calls to the logger into a single call over multiple lines. Both technically work, but we generally do the latter elsewhere.

Now that the PR is approved, please go ahead and click the "squash and merge" button to merge the changes into the develop branch. That's the job of the submitter... unless they ask that the reviewer do it for them.

Thanks Dave!

2022-05-20 20:54 UTC, merged