Feature 2206 fair crps to ecnt
dtcenter/MET pull request #2247
Opened 2022-08-30 15:22 UTC by sethlinden

## Expected Differences ##

- [x] Do these changes introduce new tools, command line arguments, or configuration file options? **[No]**</br>
If **yes**, please describe:</br>

- [x] Do these changes modify the structure of existing or add new output data types (e.g. statistic line types or NetCDF variables)? **[Yes]**</br>

If **yes**, please describe:</br>

This work adds a new column to the ECNT line type. The new variable is CRPS_EMP_FAIR.

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>

I ran unit tests for both:

  unit_ensemble_stat.xml
  unit_stat_analysis_es.xml

I looked at output from: 
 /d1/personal/linden/git/feature_2206_fair_crps_to_ecnt/MET/test_output/ensemble_stat/ensemble_stat_CMD_LINE_20120410_120000V_ecnt.txt

/d1/personal/linden/git/feature_2206_fair_crps_to_ecnt/MET/test_output/stat_analysis_es/AGG_ECNT_out.stat

I confirmed that the new variable CRPS_EMP_FAIR is showing up in the expected output files above.

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Run the unit test, check output:

  unit_ensemble_stat.xml
  unit_stat_analysis_es.xml

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**

I updated the documentation for this change to the ECNT line type (adding documentation for CRPS_EMP_FAIR).

- [x] Do these changes include sufficient testing updates? **[No]**

No changes required to unit tests, etc

- [x] Will this PR result in changes to the test suite? **[Yes]**</br>

If **yes**, describe the new output and/or changes to the existing output:</br>

Yes, a new column (CRPS_EMP_FAIR) was added to the ECNT output files

- [x] Please complete this pull request review by **[Fill in date]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [ ] After submitting the PR, select **Development** with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

2022-09-02 15:49 UTC, JohnHalleyGotway requested changes
@sethlinden it looks like there's something pretty wrong with the CRPS_EMP_FAIR values being computed. Please take a closer look at this.

Here's what I checked:
1. I downloaded the [diff file](https://github.com/dtcenter/MET/suites/8052527708/artifacts/346665585) from GHA.
2. I ran the following commands to print out the unique CRPS_EMP_FAIR values that are being reported:
```
cd ~/Downloads/diff
grep ECNT `find ./ -name *OUTPUT*.stat` > new_ECNT_lines
cat new_ECNT_lines | awk '{print $41}' | sort -nu
```
3. There are 177 updated ECNT lines:
```
cat new_ECNT_lines | wc -l
177
```
4. All of the 177 CRPS_EMP_FAIR values VERY VERY close to 0:
```
cat new_ECNT_lines | awk '{print $41}' | sort -nu
NA
1.3289e-316
6.917e-310
6.9523e-310
6.9526e-310
6.9527e-310
6.9528e-310
6.9529e-310
6.953e-310
6.9531e-310
6.9532e-310
6.9533e-310
```
I strongly suspect there's a problem in the computation. Please take a look, and once the values look reasonable, please "Re-Request" a PR review.

Recommend computing one "by-hand" to validate the computation in the code.

2022-09-12 18:04 UTC, sethlinden commented
@JohnHalleyGotway all requested changes have been made. Looked at work flow testing and the new output looks good for the CRPS_EMP_FAIR values. You can proceed to final review.

2022-09-12 19:38 UTC, JohnHalleyGotway approved these changes
I approve of these changes.

The only thing I'm not totally sure of is defining the `NumArray::wmean_abs_diff()` function. That weighting mechanism seems very specific to the computation of this one statistic and will not likely be of use elsewhere. So it probably doesn't rise to the level of importance of being implemented in the general purpose NumArray class. But it certainly isn't harming much living in there. 

Here's what I reviewed:
- Reviewed the code changes.
- Downloaded the diffs from GHA.
- Ran the following command to write the diffs (ignoring whitespace) into a single file:
```
for truth in `find ./ -name *TRUTH*`; do output=`echo $truth | sed 's/TRUTH/OUTPUT/g'`; diff -w $truth $output >> diffs; done
```
- Strip off the newly added CRPS_EMP_FAIR column from the new lines, and diff the remaining columns:
```
grep '< ' diffs | sed -r 's/ +/ /g' | cut -d' ' -f2-41 > old
grep '> ' diffs | sed -r 's/ +/ /g' | cut -d' ' -f2-41 > new
diff old new
```
No unexpected differences!
- Visually inspected to compare the CRPS_EMP and CRPS_EMP_FAIR columns for reasonable results:
```
grep '> ' diffs | sed -r 's/ +/ /g' | cut -d' ' -f39,42
```
As expected CRPS_EMP_FAIR is always slightly less than CRPS_EMP and is never < 0.
- Confirmed that changes to [Appendix C](https://met--2247.org.readthedocs.build/en/2247/Users_Guide/appendixC.html#crps) render well. 

Thanks!

2022-09-12 20:08 UTC, sethlinden commented
@JohnHalleyGotway I agree about the wmean_abs_diff() function being pretty specific to the CRPS correction. Did you want me to leave it as is, or change the name or implement the correction differently? As you alluded likely not interfering with anything but I want the code to fit the paradigm.

2022-09-13 15:59 UTC, merged