Feature 2142 ascii2nc airnow
dtcenter/MET pull request #2256
Opened 2022-09-13 17:44 UTC by davidalbo

Doing the pull request now, to make sure any desired changes can be made ASAP.  Went ahead and made input 'elevation' go to output slots for both 'elevation' and 'height'.  This can easily be changed if we get feedback on that choice. Modified the Users Guide explaining the new formats, and the config options to explain an optional environment variable for the Airnow station locations file. (tested with and without use of the environment variable).   The code is a little sloppy as regards coding standards, especially naming of members, methods, and variables, I'm not sure if we have standards for those things.  Design choices were in line with recommendations.

## Expected Differences ##

- [ ] Do these changes introduce new tools, command line arguments, or configuration file options? **[Yes or No]**</br>
If **yes**, please describe:</br> Yes, new command line argument options:  -format  airnowdaily_v2, -format airnowhourlyaqobs, -format airnowhourly.  

- [ ] Do these changes modify the structure of existing or add new output data types (e.g. statistic line types or NetCDF variables)? **[Yes or No]**</br>Maybe? 
If **yes**, please describe:</br>
 The airnow data has things like OZONE which might be new.

## Pull Request Testing ##

- [ ] Describe testing already performed for these changes:</br>
Unit tests were added for the 3 formats hourly, hourlyAqobs, and daily_v2 and the tests all passed i.e. produced output as expected.
By hand testing showed netCDF files were created with all the variables as expected.
Testing using the external 'lookup' file to find lat/lon/elev for stations showed a few stations in the hourly data file were not in the lookup file.  Warning messages are produced.

- [ ] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br> Data files in each of the 3 formats are here (seneca): /d1/projects/MET/MET_test_data/unit_test/obs_data/airnow  (The unit tests are run only on daily_data_v2.dat, HourlyAQObs_2022031200.dat, and HourlyData_2022031200.dat, all the other files can be removed if we want).  You can run tests without specifying the format, the app will figure out the format automatically. 

- [ ] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes or No]**   I think so.  

- [ ] Do these changes include sufficient testing updates? **[Yes or No]**   Yes, unit tests for all 3 formats plus extensive interactive testing in a debugger.

- [ ] Will this PR result in changes to the test suite? **[Yes or No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>  yes, 3 new unit tests:  
TEST: ascii2nc_airnow_daily_v2     - pass -   0.325 sec
TEST: ascii2nc_airnow_hourly_aqobs - pass -   0.393 sec
TEST: ascii2nc_airnow_hourly       - pass -   2.890 sec

- [ ] Please complete this pull request review by **[Up to JohnHG]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [ ] After submitting the PR, select **Development** with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

2022-09-16 20:17 UTC, j-opatz commented
While testing, it seems I'm encountering a bug where the format "airnowhourly" is not a recognized format:

`
(base) jopatz@seneca:/d1/personal/jopatz/workbench/WW3/scripts$ /d1/projects/MET/MET_pull_requests/met-11.0.0/met-11.0.0-beta3/feature_2142/MET-feature_2142_ascii2nc_airnow_into_develop/bin/ascii2nc /d1/projects/MET/MET_test_data/unit_test/obs_data/airnow/HourlyData_2022031200.dat /d1/personal/jopatz/output/testing_DELETE.nc -format airnowhourly`
`DEBUG 1: Start ascii2nc by jopatz(23784) at 2022-09-16 20:12:57Z  cmd: /d1/projects/MET/MET_pull_requests/met-11.0.0/met-11.0.0-beta3/feature_2142/MET-feature_2142_ascii2nc_airnow_into_develop/bin/ascii2nc /d1/projects/MET/MET_test_data/unit_test/obs_data/airnow/HourlyData_2022031200.dat /d1/personal/jopatz/output/testing_DELETE.nc -format airnowhourly `
```
ERROR  : 
ERROR  : set_format() -> unsupported ASCII observation format "airnowhourly".
ERROR  : 
```

However, when I pass it the file without the format flag, it seems to read it successfully.

2022-09-16 20:18 UTC, j-opatz requested changes
As noted in the comment, flag option of "airnowhourly" doesn't seem to work. Might need more investigation.

2022-09-16 20:27 UTC, davidalbo commented
@j-opatz this lack of 'airnowhourly' recognition was a bug. Do you know if I can I push changes to the branch while it is being reviewed?

2022-09-18 15:43 UTC, JohnHalleyGotway approved these changes
I approve of this PR based on @j-opatz review last week. I see that he found an issue with command line arguments and that @davidalbo has submitted a fix for that.

I also see that the only diffs flagged by GHA are from the addition of these new calls to ascii2nc.

Note that after approving, I will also merge this PR.

2022-09-18 15:43 UTC, merged