Feature #2566 v11.1.0-rc1
dtcenter/MET pull request #2573
Opened 2023-06-13 20:26 UTC by JohnHalleyGotway

## Expected Differences ##

Adds release notes for the 11.1.0-rc1 release. Also adds logic to replace '/' with '_' in the Docker tag names used by GHA. This logic was needed for the recent PR #2556 from a fork with a branch named `feature/compile_mac_clang14.x`. The '/' character is not allowed in Docker tag names.

- [x] Do these changes introduce new tools, command line arguments, or configuration file options? **[No]**</br>
If **yes**, please describe:</br>

- [x] Do these changes modify the structure of existing or add new output data types (e.g. statistic line types or NetCDF variables)? **[No]**</br>
If **yes**, please describe:</br>

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
Confirmed that GHA successfully compiles with the code even with the script changes.

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
Please review release notes [here](https://met.readthedocs.io/en/feature_2566_v11.1.0-rc1/Users_Guide/release-notes.html#met-version-11-1-0-rc1-release-notes-20230613)

I listed the date as tomorrow (20230614) since it's not getting done today.

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**

- [x] Do these changes include sufficient testing updates? **[Yes]**

- [x] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [x] Please complete this pull request review by **[20230614]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Review the source issue metadata (required labels, projects, and milestone).
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)**
Select: **Organization** level software support **Project** or **Repository** level development cycle **Project**
Select: **Milestone** as the version that will include these changes
- [x] After submitting the PR, select **Development** issue with the original issue number.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

2023-06-13 21:38 UTC, georgemccabe requested changes
The compilation step fails because it is setting the DockerHub tag to the string `get_dockerhub_tag`. 

> The push refers to repository [docker.io/library/get_dockerhub_tag]

I made suggested changes that I think should fix it. I tested them in a bash shell locally.

2023-06-13 21:38 UTC, georgemccabe commented on .github/jobs/bash_functions.sh
> +  tag_name=`echo ${DOCKERHUB_REPO}:${SOURCE_BRANCH} | sed 's%/%_%g'`
```suggestion
  echo ${DOCKERHUB_REPO}:${SOURCE_BRANCH} | sed 's%/%_%g';
```
You can't return a string in a bash function, so just echo the value

2023-06-13 21:38 UTC, georgemccabe commented on .github/jobs/bash_functions.sh
> +  return $tag_name;
```suggestion
```
Remove this return

2023-06-13 21:38 UTC, georgemccabe commented on .github/jobs/build_docker_image.sh
> +DOCKERHUB_TAG=get_dockerhub_tag
```suggestion
DOCKERHUB_TAG=`get_dockerhub_tag`
```
With the above changes, the function will echo the value and this change will set the echo'd value to the DOCKERHUB_TAG variable.

2023-06-13 23:14 UTC, JohnHalleyGotway commented
Thanks for catching these issues. Sorry, don’t know how I missed this. I could’ve sworn that it complied fine via GHA but perhaps I just saw the successful documentation workflow run? I’ll get this patched up tomorrow and merge after a successful compilation.

2023-06-14 16:45 UTC, JohnHalleyGotway commented
Re-requesting review. The [GHA run](https://github.com/dtcenter/MET/actions/runs/5269432626/jobs/9528400206?pr=2573) compiled fine. It does flag diffs but those are related to recently approved PR's and not this one.

2023-06-14 17:02 UTC, georgemccabe approved these changes
The compilation step is now working properly.
I reviewed the release notes and they look good. All items are descriptive and clear. The links are all correct as well.
I approve.

2023-06-14 17:18 UTC, merged