Feature 2716 headers
dtcenter/MET pull request #2725
Opened 2023-11-06 16:11 UTC by lisagoodrich

## Expected Differences ##

- [x] Do these changes introduce new tools, command line arguments, or configuration file options? **No**</br>
If **yes**, please describe:</br>

- [x] Do these changes modify the structure of existing or add new output data types (e.g. statistic line types or NetCDF variables)? **[No]**</br>
If **yes**, please describe:</br>

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
Overall this process went smoothly.  
Most of the headers were already correct.  Many of the headers needed to be capitalized to keep our formatting consistent.  As usual, there were some exceptions. 

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>

Please double check all of the index.rst files.  I think they are correct but I'd appreciate a second set of eyes on this.
docs/index.rst
docs/Users_Guide/index.rst
docs/Contributors_Guide/index.rst
___________________

https://met.readthedocs.io/en/feature_2716_headers/Users_Guide/stat-analysis.html

I think I made the right call on these.  I'm leaving them lowercase. Per Julie, this is correct.
16.3.3.1. Job: filter
16.3.3.2. Job: summary
Job: thing_it's_doing_etc.
 
_____________________________

I didn't capitalize the questions, since they are questions.  (But they are also headers so I thought it was worth discussing.)

https://met.readthedocs.io/en/feature_2716_headers/Users_Guide/appendixA.html 
Julie: I agree that they should not be capitalized.  Thanks for asking about things that aren't clear and where there could be more than one acceptable answer.

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[No, there are no errors]**

- [x] Do these changes include sufficient testing updates? **[Yes]**

- [x] Will this PR result in changes to the test suite? **[No]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>

- [ ] Please complete this pull request review by **11/10/23**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Review the source issue metadata (required labels, projects, and milestone).
- [ ] Complete the PR definition above.
- [ ] Ensure the PR title matches the feature or bugfix branch name.
- [ ] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the version that will include these changes
Select: **Coordinated METplus-X.Y Support** project for bugfix releases or **MET-X.Y.Z Development** project for official releases
- [ ] After submitting the PR, select the :gear: icon in the **Development** section of the right hand sidebar. Search for the issue that this PR will close and select it, if it is not already selected.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

2023-11-06 18:27 UTC, jprestop commented on docs/Contributors_Guide/dev_details/index.rst
> +###################
```suggestion
*******************
```

2023-11-06 18:28 UTC, jprestop commented on docs/Contributors_Guide/dev_details/index.rst
> +###################
Development Details is at the same level as the chapter Development Environment and should have the same header.
https://met.readthedocs.io/en/feature_2716_headers/Contributors_Guide/index.html

2023-11-06 18:31 UTC, jprestop commented on docs/Contributors_Guide/dev_details/index.rst
> +###################
```suggestion
*******************
```

2023-11-06 18:31 UTC, jprestop commented on docs/Contributors_Guide/dev_details/tmp_file_use.rst
> +**********************
```suggestion
```

2023-11-06 18:31 UTC, jprestop commented on docs/Contributors_Guide/dev_details/tmp_file_use.rst
> +**********************
```suggestion
======================
```

2023-11-06 18:31 UTC, jprestop commented on docs/Contributors_Guide/dev_details/tmp_file_use.rst
> +==========
```suggestion
^^^^^^^^^^
```

2023-11-06 18:32 UTC, jprestop commented on docs/Contributors_Guide/dev_details/tmp_file_use.rst
> +===============
```suggestion
^^^^^^^^^^^^^^^
```

2023-11-06 18:32 UTC, jprestop commented on docs/Contributors_Guide/dev_details/tmp_file_use.rst
> +==============================
```suggestion
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

2023-11-06 18:32 UTC, jprestop commented on docs/Contributors_Guide/dev_details/tmp_file_use.rst
> +==================
```suggestion
^^^^^^^^^^^^^^^^^^
```

2023-11-06 18:33 UTC, jprestop commented on docs/Contributors_Guide/dev_details/tmp_file_use.rst
> +================
```suggestion
^^^^^^^^^^^^^^^^
```

2023-11-06 18:33 UTC, jprestop commented on docs/Contributors_Guide/dev_details/tmp_file_use.rst
> +============
```suggestion
^^^^^^^^^^^^
```

2023-11-06 18:35 UTC, jprestop commented on docs/Users_Guide/appendixC.rst
> +Which Statistics are the Same, but with Different Names?
```suggestion
Which statistics are the same, but with different names?
```

2023-11-06 18:51 UTC, jprestop commented on docs/Users_Guide/masking.rst
> +Regional Verification Using Spatial Masking
```suggestion
Regional Verification using Spatial Masking
```

2023-11-06 18:57 UTC, jprestop commented on docs/index.rst
> +-----
```suggestion
=====
```
Change back to original

2023-11-06 19:05 UTC, jprestop commented
@lisagoodrich I changed the Milestone to MET-12.0.0.

2023-11-06 19:07 UTC, jprestop requested changes
Hi @lisagoodrich. I have requested some changes.  When you're finished with the changes and ready for me to re-review, please click on the circular arrow icon next to my name as shown in this screenshot to let me know you're ready for a re-review.
<img width="337" alt="Screen Shot 2023-11-06 at 12 05 14 PM" src="https://github.com/dtcenter/MET/assets/11999822/76d6b582-d121-4f4a-b43b-8186b3982df2">

2023-11-09 20:31 UTC, lisagoodrich commented
@jprestop I have made all of the changes.  I think we're good.  Do I squash and merge or would you like to do that?

2023-11-09 20:33 UTC, jprestop commented
Hi @lisagoodrich. I haven't approved it yet, since I had requested changes. I'll approve it now and will just go ahead and squash and merge for you as I know you're on your way out the door now.

2023-11-09 20:33 UTC, jprestop approved these changes
@lisagoodrich Thank you for making these changes and updates.  All tests have passed. I approve this request.

2023-11-09 20:33 UTC, merged