Feature #2833 pcp_combine_missing
dtcenter/MET pull request #2886
Opened 2024-05-11 16:42 UTC by JohnHalleyGotway

## Expected Differences ##

- [x] Do these changes introduce new tools, command line arguments, or configuration file options? **[Yes]**</br>
If **yes**, please describe:</br>
Adds new `-input_thresh` command line option for pcp_combine which is supported for the `-add`, `-derive`, and `-sum` options. It's NOT supported for `-subtract` for which exactly two valid input files are required.

- [x] Do these changes modify the structure of existing or add new output data types (e.g. statistic line types or NetCDF variables)? **[No]**</br>
If **yes**, please describe:</br>

## Pull Request Testing ##

- [x] Describe testing already performed for these changes:</br>
Added 1 new `pcp_combine_sum_GRIB1_MISSING` test in `unit_pcp_combine.xml` to demonstrate running `-sum` with one of the 4 expected inputs missing but `-input_thresh 0.75` set to allow output to be written.

Modified 1 existing `pcp_combine_derive_MULTIPLE_FIELDS` test in `unit_pcp_combine.xml` to demonstrate running `-derive` with missing inputs files at the beginning, middle, and end of the input file list. The first 2 do not trigger warnings because the MISSING keyword is used. The 3rd does, because MISSING is not present in the path.

- [x] Recommend testing for the reviewer(s) to perform, including the location of input datasets, and any additional instructions:</br>
Please review the code changes, documentation updates, and testing changes.

- [x] Do these changes include sufficient documentation updates, ensuring that no errors or warnings exist in the build of the documentation? **[Yes]**

- [x] Do these changes include sufficient testing updates? **[Yes]**

- [x] Will this PR result in changes to the MET test suite? **[Yes]**</br>
If **yes**, describe the new output and/or changes to the existing output:</br>
One new output file named `pcp_combine/nam_2012040900_F087_APCP12.nc` is created.

- [x] Will this PR result in changes to existing METplus Use Cases? **[No]**</br>
If **yes**, create a new **Update Truth** [METplus issue](https://github.com/dtcenter/METplus/issues/new/choose) to describe them.

- [x] Do these changes introduce new SonarQube findings? **[Yes or No]**</br>
If **yes**, please describe:
I don't know. If the GHA run for this PR triggers them, I'll go fix them.

- [x] Please complete this pull request review by **[Tues 5/14/24]**.</br>

## Pull Request Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [x] Review the source issue metadata (required labels, projects, and milestone).
- [x] Complete the PR definition above.
- [x] Ensure the PR title matches the feature or bugfix branch name.
- [x] Define the PR metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the version that will include these changes
Select: **Coordinated METplus-X.Y Support** project for bugfix releases or **MET-X.Y.Z Development** project for official releases
- [x] After submitting the PR, select the :gear: icon in the **Development** section of the right hand sidebar. Search for the issue that this PR will close and select it, if it is not already selected.
- [ ] After the PR is approved, merge your changes. If permissions do not allow this, request that the reviewer do the merge.
- [ ] Close the linked issue and delete your feature or bugfix branch from GitHub.

2024-05-13 15:45 UTC, georgemccabe requested changes
These changes look good. I made a few minor suggestions for the documentation and usage statement.

2024-05-13 15:45 UTC, georgemccabe commented on docs/Users_Guide/reformat_grid.rst
> +5. The **-input_thresh n** option overrides the default required ratio of valid input files. This option does not apply to the -sub command where exactly two valid inputs are required. The default is
```suggestion
5. The **-input_thresh n** option overrides the default required ratio of valid input files. This option does not apply to the -subtract command where exactly two valid inputs are required. The default is 1.0.
```

2024-05-13 15:45 UTC, georgemccabe commented on src/tools/core/pcp_combine/pcp_combine.cc
>          << "of valid data (" << vld_thresh << ") (optional).\n"
Consider refining this to make it more clear the distinction between input and vld thresh
```suggestion
        << "of valid data at a grid point (" << vld_thresh << ") (optional).\n"
```

2024-05-13 15:54 UTC, JohnHalleyGotway commented on src/tools/core/pcp_combine/pcp_combine.cc
>          << "of valid data (" << vld_thresh << ") (optional).\n"
Updated via a change to my branch. Thanks.

2024-05-13 17:14 UTC, georgemccabe requested changes
It looks like the `pcp_combine_derive_VLD_THRESH` unit test is failing because the previous test was modified to change the list of input files to include missing paths and this test uses the same file list file. To fix this we could either:
1) Create another file list text file that matches the previous list to use in this test
OR
2) Add the `-input_thresh` argument to this test

It looks like the SonarQube test also failed.

2024-05-13 17:40 UTC, JohnHalleyGotway commented
Converted PR to draft while I fix the tests and SonarQube findings.

2024-05-13 22:02 UTC, JohnHalleyGotway commented
@georgemccabe I just reopened this PR after fixing the testing and SonarQube issues.

Note that [14 SonarQube code smells](https://needham.rap.ucar.edu/dashboard?id=MET&branch=refs%2Fpull%2F2886%2Fmerge) remain for this PR, but these are ones I do not plan to fix. They're not easy, and I confirmed with Julie and Michelle that these don't have a high enough priority level to be worked on right now.

I do expect differences in the output to be flagged, but only based on the addition of 1 new file.

2024-05-14 12:59 UTC, georgemccabe requested changes
It looks like another unit test is failing: python_pcp_combine_SEMILATLON_MERIDIONAL_MEAN

2024-05-15 15:00 UTC, JohnHalleyGotway commented
Phew, OK, this[ testing workflow run](https://github.com/dtcenter/MET/actions/runs/9087391809/job/24975748978) now completes all the tests and only flags one new output file, as expected:
```
ERROR: folder /data/output/met_test_truth missing 1 files
    pcp_combine/nam_2012040900_F087_APCP12.nc 
```
The updated logic in `parse_file_list.cc` is working as expected.
This PR is ready to be re-reviewed.

2024-05-15 15:05 UTC, georgemccabe approved these changes
Looks good, thanks for making those fixes.

2024-05-15 19:33 UTC, merged